"""empty message

Revision ID: 07539abacf1a
Revises: 1b5a056c9bff
Create Date: 2024-08-01 15:32:56.666026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07539abacf1a'
down_revision = '1b5a056c9bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('product_price')

    # ### end Alembic commands ###
