"""add user id

Revision ID: 459095754406
Revises: 07539abacf1a
Create Date: 2024-08-01 16:42:18.515594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459095754406'
down_revision = '07539abacf1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
